
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by HiLang
//
// You can not modify this code as we will overwrite it when project built
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using Hiperspace;
using ProtoBuf;
using System.Collections;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;

namespace Hiperspace.Meta
{

    #region MapMap

    [ProtoContract]

    public partial struct MapMap
    {
        internal KeyType _key;
        internal ValueType _value;
        internal bool _bound = false;

        public MapMap()
        {

            _key = new KeyType();
            _value = new ValueType();



        }
        internal MapMap(KeyType key, ValueType value) : this()
        {
            _key = key;
            _value = value;
        }
        internal MapMap(KeyType key) : this()
        {
            _key = key;
        }
        public MapMap(MapMap source) : this()
        {
            _key = source._key;
            _value = source._value;
        }



        [ProtoMember(2)]
        public List<Hiperspace.Meta.MapElement>? Map
        {
            get
            {
                return _value.Map;
            }
            set
            {
                if (_bound && _value.Map != value) throw new Hiperspace.ValueMutationException($"Map");
                _value.Map = value;
            }
        }

        #region state

        [ProtoContract]
        public struct KeyType : IEquatable<KeyType>, IComparable<KeyType>
        {
            internal KeyType(MapMap item)
            {

            }


            public bool IsGetable()
            {

                return true;
            }
            public bool IsSargable()
            {

                return false;
            }
            public string SKey => ""; // Values can't have string keys
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public void Bind(SubSpace space)
            {

            }
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public void Unbind(SubSpace space)
            {

            }
            public bool Equals(KeyType other)
            {
                if (this == other) return true;
                return false;
            }
            public override bool Equals(Object? other)
            {
                if (other is null) return false;
                if (other is KeyType) return Equals((KeyType)other);
                return false;
            }
            private int? _hashCode;
            public override int GetHashCode()
            {
                if (_hashCode.HasValue) return _hashCode.Value;
                HashCode hc = new HashCode();

                _hashCode = hc.ToHashCode();
                return _hashCode.Value;
            }

            public int CompareTo(KeyType other)
            {
                if (this < other) return -1;
                if (this > other) return 1;
                return 0;
            }
            public static bool operator ==(KeyType left, KeyType right)
            {

                return true;
            }
            public static bool operator !=(KeyType left, KeyType right)
            {
                return !(left == right);
            }
            public static bool operator <(KeyType left, KeyType right)
            {

                return false;
            }
            public static bool operator >(KeyType left, KeyType right)
            {

                return false;
            }
        }
        public static explicit operator KeyType(MapMap item) => item._key;

        [ProtoContract]
        public struct ValueType
        {
            internal ValueType(MapMap item)
            {

                Map = item.Map;
            }

            [ProtoMember(2)] public List<Hiperspace.Meta.MapElement>? Map;
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public void Bind(SubSpace space)
            {

                if (Map is not null) foreach (var p1 in Map) p1.Bind(space);

            }
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public void Unbind(SubSpace space)
            {

                if (Map is not null) foreach (var p1 in Map) p1.Unbind(space);
            }
            public bool Equals(ValueType other)
            {
                if (this == other) return true;
                return false;
            }
            public override bool Equals(Object? other)
            {
                if (other is null) return false;
                if (other is ValueType) return Equals((ValueType)other);
                return false;
            }
            public override int GetHashCode()
            {
                HashCode hc = new HashCode();

                hc.Add(Map);
                return hc.ToHashCode();
            }

            public static bool operator ==(ValueType left, ValueType right)
            {

                if (left.Map?.Equals(right.Map) == false) return false;
                return true;
            }
            public static bool operator !=(ValueType left, ValueType right)
            {
                return !(left == right);
            }
        }
        public static explicit operator ValueType(MapMap item) => item._value;

        #endregion

        #region Extents




        #endregion

        #region Entity
        public Result<MapMap> Bind(SubSpace subSpace)
        {
            if (subSpace is SubSpace space)
            {
                _key.Bind(space);
                _value.Bind(space);
                _bound = true;



            }
            return Result.Skip(this);
        }
        public void Unbind(SubSpace subSpace)
        {
            if (subSpace is SubSpace space)
            {
                _key.Unbind(space);
                _value.Unbind(space);
                _bound = false;



            }
        }

        public override int GetHashCode()
        {
            return HashCode.Combine(_key.GetHashCode(), _value.GetHashCode());
        }
        public bool Equals(MapMap? other)
        {
            if (other is null)
                return false;
            return (_key == other.Value._key && _value == other.Value._value);
        }
        public override bool Equals(Object? other)
        {
            if (other is null) return false;
            if (other is MapMap) return Equals((MapMap)other);
            return false;
        }
        public int CompareTo(MapMap? other)
        {
            if (other is null)
                throw new ArgumentNullException(nameof(other));
            if (_key < other.Value._key)
                return -1;
            else if (_key > other.Value._key)
                return 1;
            else
                return 0;
        }
        public static bool operator ==(MapMap left, MapMap right)
        {
            if (left._key.Equals(right._key) != true) return false;
            return true;
        }
        public static bool operator !=(MapMap left, MapMap right)
        {
            return !(left == right);
        }
        public static bool operator <(MapMap left, MapMap right)
        {
            if (left._key < right._key) return false;
            return false;
        }
        public static bool operator >(MapMap left, MapMap right)
        {
            if (left._key > right._key) return false;
            return false;
        }
        #endregion
        public (int key, (int member, int key)[] values)[] ToMap()
        {
            var pairs = Map?.Select(i => i.ToMap()).ToArray() ?? Array.Empty<(int key, (int member, int key)[] values)>();
            Array.Sort(pairs);
            return pairs;
        }
    }
    #endregion
}
